# Generated by Django 5.0.2 on 2024-05-27 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("operators", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="coverage",
            name="operators_c_operato_561308_idx",
        ),
    ]
